### ISSUE TITLE
Error: This is not a valid feed template

### ISSUE THREAD

**Issue by yogeshbeniwal** [artprojectgroup/google-image-sitemap-feed-with-multisite-support#3]
v2 is resulting in below error

`
<error>
    <code>wp_die</code>
    <title><![CDATA[WordPress &amp;rsaquo; Error]]></title>
    <message><![CDATA[&lt;strong&gt;Error&lt;/strong&gt;: This is not a valid feed template.]]></message>
    <data>
        <status>404</status>
    </data>
</error>
`

**Comment by artprojectgroup** [comment]
Make sure your plugin is active.

Best regards.
